version: "3"
services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    depends_on:
      - nodeserver
    links:
      - "nodeserver:be"
    volumes:
      - /app/node_modules
      - ./Frontend:/app

  chiselserver:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports: 
      - '8080:8080'
    tty: true

  nodeserver:
    build:
      context: ./Backend_nodeJS
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    depends_on: 
      - chiselserver
    volumes:
      - /app/node_modules
      - ./Backend_nodeJS:/app
    environment:
      CHISELHOST: chiselserver

  nginx:
    depends_on:
      - nodeserver
      - client
      - chiselserver
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
