version: "3"
services:
  seereye:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./seereye
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - nodeserver
      - flutter
    links:
      - "nodeserver:be"
      - "flutter:bi"
    volumes:
      - /app/node_modules
      - ./seereye:/app

  flutter:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./seereye-app
    ports:
      - '3003:80'
    volumes:
      - ./seereye:/app

  nodeserver:
    build:
      context: ./nodeserver
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./nodeserver:/app
    ports:
      - '5000:5000'

  nginx:
    depends_on:
      - nodeserver
      - seereye
      - flutter
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
