version: "3"
services:

  rexys:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./rexys
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    depends_on:
      - nodeserver
    links:
      - "nodeserver:be"
      # - "flutter:be"
    container_name: rexys
    volumes:
      - /app/node_modules
      - ./rexys:/app

  seereye:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./seereye
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - nodeserver
    links:
      - "nodeserver:be"
    container_name: seereye
    volumes:
      - /app/node_modules
      - ./seereye:/app

  flutter:
    build:
      context: ./seereye-app/seereye_app
    ports:
      - '3003:80'
    volumes:
      - ./seereye-app:/app

  nodeserver:
    build:
      context: ./nodeserver
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./nodeserver:/app
    ports:
      - '5000:5000'
    container_name: nodeserver

  nginx:
    depends_on:
      - nodeserver
      - seereye
      # - flutter
      - rexys
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "4000:80"

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'