# build environment
FROM node:14-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN npx browserslist@latest --update-db
RUN yarn install --frozen-lockfile
RUN yarn global add react-scripts@4.0.3
COPY . ./

RUN yarn build
